import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { motion } from 'framer-motion';
import { Award, Target, Trophy, Flame, ChevronRight, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

// Animated Counter Component
const AnimatedCounter = ({ value, duration = 2 }) => {
  const [count, setCount] = useState(0);

  useEffect(() => {
    let startTimestamp = null;
    const step = (timestamp) => {
      if (!startTimestamp) startTimestamp = timestamp;
      const progress = Math.min((timestamp - startTimestamp) / (duration * 1000), 1);
      setCount(Math.floor(progress * value));
      if (progress < 1) {
        window.requestAnimationFrame(step);
      }
    };
    window.requestAnimationFrame(step);
  }, [value, duration]);

  return <span>{count}</span>;
};

const EmployeeDashboard = () => {
  const { currentUser } = useAuth();
  const navigate = useNavigate();

  // Mock data for employee
  const currentPoints = 850;
  const nextTierPoints = 1000;
  const progressPercent = (currentPoints / nextTierPoints) * 100;
  const rank = 4;
  
  return (
    <div className="space-y-8 pb-16 md:pb-0">
      
      {/* Welcome Banner */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass-card relative overflow-hidden bg-gradient-to-r from-primary/10 to-secondary/10 border-primary/20"
      >
        <div className="absolute right-[-10%] top-[-50%] w-64 h-64 bg-secondary/20 rounded-full blur-3xl" />
        
        <div className="flex flex-col md:flex-row items-center gap-6 relative z-10">
          <div className="relative group">
            <div className="absolute inset-0 bg-primary/20 rounded-full blur-xl group-hover:bg-primary/40 transition-colors duration-500"></div>
            <img src={currentUser?.avatar || 'https://i.pravatar.cc/150?u=a042581f4e29026024d'} alt="Profile" className="relative w-24 h-24 rounded-full border-4 border-card shadow-xl object-cover" />
            <div className="absolute -bottom-2 -right-2 bg-gradient-to-br from-slate-200 to-slate-300 text-slate-800 text-xs font-bold px-3 py-1 rounded-full border-2 border-card shadow-lg flex items-center gap-1.5 z-20">
              <Trophy size={14} className="text-amber-600" /> Silver
            </div>
          </div>
          
          <div className="flex-1 text-center md:text-left">
            <h1 className="text-2xl md:text-3xl font-bold text-slate-900 dark:text-white mb-1">
              Hello, {currentUser?.name}! 👋
            </h1>
            <p className="text-slate-600 dark:text-slate-300 mb-4 max-w-xl">
              "Success is not final, failure is not fatal: it is the courage to continue that counts." — <span className="text-xs opacity-50">Generated by Gemini AI</span>
            </p>
          </div>
          
          <div className="bg-card/50 backdrop-blur-md border border-white/10 p-5 rounded-2xl text-center min-w-[160px] shadow-xl relative overflow-hidden group">
            <div className="absolute inset-0 bg-gradient-to-tr from-amber-500/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
            <p className="text-sm text-slate-500 dark:text-slate-400 font-medium mb-1">Company Rank</p>
            <div className="flex items-center justify-center gap-2 relative z-10">
              <Award className="text-amber-500" size={28} />
              <span className="text-4xl font-bold text-slate-900 dark:text-white font-display">#{rank}</span>
            </div>
          </div>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
        
        {/* Points & Progress (Left Column) */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.1 }}
          onClick={() => navigate('/employee/rewards')}
          className="md:col-span-7 glass-card flex flex-col justify-center relative overflow-hidden cursor-pointer group hover:border-primary/30 transition-all duration-300"
        >
          <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-full -mr-16 -mt-16 transition-transform group-hover:scale-110" />
          <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity text-primary">
            <ArrowRight size={20} />
          </div>
          
          <h2 className="text-lg font-semibold text-slate-800 dark:text-slate-200 mb-6 flex items-center gap-2">
            <Target className="text-primary" size={20} />
            Your Reward Points
          </h2>
          
          <div className="flex items-end gap-2 mb-2">
            <span className="text-6xl font-black text-transparent bg-clip-text bg-gradient-to-r from-primary to-indigo-400">
              <AnimatedCounter value={currentPoints} />
            </span>
            <span className="text-slate-500 dark:text-slate-400 font-medium pb-2">/ {nextTierPoints} pts</span>
          </div>
          
          <div className="mt-8">
            <div className="flex justify-between text-sm font-medium mb-2">
              <span className="text-slate-500">Silver Tier</span>
              <span className="text-amber-500">Gold Tier next</span>
            </div>
            
            {/* Progress Bar Container */}
            <div className="h-4 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden shadow-inner">
              <motion.div 
                initial={{ width: 0 }}
                animate={{ width: `${progressPercent}%` }}
                transition={{ duration: 1.5, ease: "easeOut", delay: 0.5 }}
                className="h-full bg-gradient-to-r from-primary to-secondary relative"
              >
                {/* Shine effect on progress bar */}
                <div className="absolute top-0 left-0 w-full h-full bg-white/20 animate-pulse" />
              </motion.div>
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-3 text-right">
              {nextTierPoints - currentPoints} points away from Gold!
            </p>
          </div>
        </motion.div>

        {/* AI Insights & Badges (Right Column) */}
        <div className="md:col-span-5 space-y-6">
          
          {/* AI Insight Mini */}
          <motion.div 
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
            className="glass-card bg-gradient-to-br from-indigo-50/50 to-white/5 dark:from-indigo-900/10 dark:to-slate-900/50 border border-indigo-500/20"
          >
            <div className="flex items-start gap-4">
              <div className="p-3 bg-gradient-to-br from-indigo-500/20 to-purple-500/20 rounded-xl text-indigo-600 dark:text-indigo-400 shadow-inner">
                <Flame size={24} />
              </div>
              <div>
                <h3 className="font-semibold text-slate-800 dark:text-slate-200">AI Performance Tip</h3>
                <p className="text-sm text-slate-600 dark:text-slate-400 mt-2 leading-relaxed">
                  You're on a 3-month perfect attendance streak! Maintain this to automatically earn the <span className="font-semibold text-amber-500 bg-amber-500/10 px-1.5 py-0.5 rounded-md">Consistency Badge</span> next week.
                </p>
              </div>
            </div>
          </motion.div>

          {/* Badges Preview */}
          <motion.div 
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 }}
            onClick={() => navigate('/employee/badges')}
            className="glass-card cursor-pointer group hover:border-primary/30 transition-all duration-300"
          >
            <div className="flex justify-between items-center mb-4">
              <h3 className="font-semibold text-slate-800 dark:text-slate-200">Recent Badges</h3>
              <button className="text-xs text-primary group-hover:translate-x-1 transition-transform flex items-center">
                View All <ChevronRight size={14} />
              </button>
            </div>
            
            <div className="grid grid-cols-4 gap-3">
              <div className="flex flex-col items-center justify-center p-3 bg-amber-50 dark:bg-amber-900/10 border border-amber-100 dark:border-amber-900/30 rounded-xl group-hover:scale-105 transition-transform">
                <span className="text-3xl filter drop-shadow-md">🌟</span>
              </div>
              <div className="flex flex-col items-center justify-center p-3 bg-green-50 dark:bg-green-900/10 border border-green-100 dark:border-green-900/30 rounded-xl group-hover:scale-105 transition-transform">
                <span className="text-3xl filter drop-shadow-md">📅</span>
              </div>
              <div className="flex flex-col items-center justify-center p-3 bg-blue-50 dark:bg-blue-900/10 border border-blue-100 dark:border-blue-900/30 rounded-xl group-hover:scale-105 transition-transform">
                <span className="text-3xl filter drop-shadow-md">🤝</span>
              </div>
              <div className="flex flex-col items-center justify-center p-3 bg-slate-50 dark:bg-slate-800 border border-slate-100 dark:border-slate-700 rounded-xl opacity-50 grayscale">
                <span className="text-3xl">💡</span>
              </div>
            </div>
          </motion.div>

        </div>
      </div>
      
    </div>
  );
};

export default EmployeeDashboard;
